# Dockerfile
FROM python:3.11-slim

# current working dir
WORKDIR /jenkins-with-docker/app                  

# = COPY jenkins-d.py /app/jenkins-d.py
COPY jenkins-d.py . 
CMD ["python", "jenkins-d.py"]
