# Dockerfile
FROM python:3.11-slim
WORKDIR /jenkins-with-docker/app                  // current working dir
COPY jenkins-d.py .           // = COPY jenkins-d.py /app/jenkins-d.py
CMD ["python", "jenkins-d.py"]
